### ISSUE TITLE
All agents cowering can lead to non-ending game

### ISSUE THREAD

**Issue by EdvardJSHolen** [SOMAS2022/SOMAS2022#49] opened 2022-11-18 00:53 UTC
If all currently alive agents cower continuously, this can lead to situation where the agents regain more health per round than the amount of damage the monster does. As such, it is possible to end up in situations where the game never finishes. Can be fixed by simply making the game time out after some set duration.

**Comment by Razvan00Rusu** [comment] 2022-11-18 01:52
I mentioned in [this TODO](https://github.com/SOMAS2022/SOMAS2022/blob/469627482a317b448120b1153a484109a7e28931/pkg/infra/main.go#L48). In short, the original spec mentioned some sort of round-limit, i.e. the agents would only be able to cower n number of times in each level. 

When working on this, I was unsure if this was being taken forward from the original spec to our spec so it isn't implemented.

**Comment by 0x6770** [comment] 2022-11-18 02:07
Aside from round limit, maybe config the monster to cause more damage or reduce the amount of HP regain by covering is more guaranteed?

**Comment by BusterBlack** [comment] 2022-11-19 01:18
this wont be the case once the new maths is implemented... the monster will always deal more damage to each agent than the agent will get from cowering. (in theory)

**Comment by neeldug** [comment] 2022-11-19 01:22
Closing as somewhat of a duplicate of #18.

**Closed by neeldug** 2022-11-19 01:22 UTC
Labels: bug, infra
